services:
  bragibooks:
    image: bragibooks:local
    ports:
      - '8888:8080'
    volumes:
      - ./config:/app/config
      - /home/djdembeck:/home/djdembeck
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - DATABASE_PATH=config/bragibooks.db
      - DIRECTORIES_INPUT_DIR=/input
      - DIRECTORIES_OUTPUT_DIR=/output
      - DIRECTORIES_COMPLETED_DIR=/input/done
      - PROCESSING_REGION=us
    restart: unless-stopped
