FROM golang:1.26-alpine

RUN apk add --no-cache git ffmpeg
RUN go install github.com/air-verse/air@latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

COPY --from=ghcr.io/djdembeck/m4b-merge:main-amd64 /usr/local/bin/m4b-merge /usr/local/bin/m4b-merge

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]