services:
  bragibooks:
    image: bragibooks:local
    ports:
      - '8888:8080'
    volumes:
      - ./config:/app/config
      - /home/djdembeck:/home/djdembeck
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - DATABASE_PATH=config/bragibooks.db
    restart: unless-stopped