# Generated by Django 3.2.5 on 2021-11-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.CharField(max_length=255)),
                ('completed_directory', models.CharField(max_length=255)),
                ('input_directory', models.CharField(max_length=255)),
                ('num_cpus', models.IntegerField()),
                ('output_directory', models.CharField(max_length=255)),
                ('output_scheme', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
