# Generated by Django 4.0.1 on 2022-01-10 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0002_setting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
